name: Daily Script to check special days

on:
  schedule:
    # Runs daily at midnight (UTC)
    - cron: "0 0 * * *"

jobs:
  run-app-script:
    runs-on: ubuntu-latest

    env:
      BIRTHDAY_TOKEN: ${{ secrets.BIRTHDAY_TOKEN }}
      ANNIVERSIRY_TOKEN: ${{ secrets.ANNIVERSIRY_TOKEN }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # replicating node version locally

      - name: Install Dependencies
        run: npm install

      - name: Run special day checks
        run: node app.js
